server:
  port: 8080

management:
  endpoint:
    health:
      show-details: ALWAYS
  health:
    binders:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - bindings
          - prometheus
          - "*"

#logging:
  #level:
    #root: DEBUG

spring:
  cloud:
    stream:
      function:
        definition: process
        bindings:
          process-in-0:
            destination: tp-prospects
          process-in-1:
            destination: tp-accounts
          process-in-2:
            destination: tp-enrichment-accounts
          process-out-0:
            destination: tp-clients
      kafka:
        streams:
          binder:
            applicationId: streams
            #brokers: broker:9093
            brokers: kafka-cluster-kafka-bootstrap.kafka-streams.svc.cluster.local:9092
            #brokers: localhost:9092
            #brokers: localhost:32069
            configuration:
              #num:
                #stream:
                  #threads: 2
              #state.dir: state-store
              commit.interval.ms: 500
          bindings:
            tp_prospects:
              consumer:
                materializedAs: tp-prospects-state-store
            tp_accounts:
              consumer:
                materializedAs: tp-accounts-state-store
            tp_enrichment_accounts:
              consumer:
                materializedAs: tp-enrichment-accounts-state-store
