apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-streams-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-streams-spring-boot
  template:
    metadata:
      labels:
        app: kafka-streams-spring-boot
    spec:
      containers:
        - name: kafka-streams-spring-boot
          image: kafka-streams-spring-boot:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-streams-spring-boot
  labels:
    app: kafka-streams-spring-boot
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8080
  selector:
    app: kafka-streams-spring-boot
---      
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-streams-spring-boot-monitor
  labels:
    app: kafka-streams-spring-boot
spec:
  endpoints:
  - interval: 30s
    path: /actuator/prometheus
    port: web
  namespaceSelector:
    matchNames:
    - kafka-streams
  selector:
    matchLabels:
      app: kafka-streams-spring-boot