apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-streams-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-streams-spring-boot
  template:
    metadata:
      labels:
        app: kafka-streams-spring-boot
    spec:
      containers:
        - name: kafka-streams-spring-boot
          image: kafka-streams-spring-boot:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-streams-spring-boot
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kafka-streams-spring-boot